// Rich initial mock dataset for HealthFlow
import { IMAGES } from '../constants/images';

export const INITIAL_USER = {
  id: 'user-001',
  name: 'Firdavs Abdurazzakov',
  firstName: 'Firdavs',
  email: 'firdavs@healthflow.app',
  phone: '+1 (555) 349-8821',
  avatar: IMAGES.avatars.firdavs,
  bloodType: 'O+',
  age: 28,
  height: '182 cm',
  weight: '76 kg',
  allergies: ['Penicillin', 'Peanuts (Mild)'],
  conditions: ['Mild Seasonal Asthma'],
  insuranceProvider: 'BlueCross Horizon Platinum #HC-88912',
  emergencyContact: {
    name: 'Aziza Karimova',
    relation: 'Spouse',
    phone: '+1 (555) 234-5678',
  },
  preferences: {
    theme: 'light', // 'light' | 'dark'
    notifications: {
      medicationReminders: true,
      habitCheckIns: true,
      weeklyReport: true,
      emergencyAlerts: true,
      soundEnabled: true,
    },
    privacy: {
      shareAnalytics: false,
      biometricLock: false,
      dataRetentionDays: 365,
    },
  },
};

export const INITIAL_HABITS = [
  {
    id: 'habit-1',
    title: 'Hydration Goal',
    category: 'hydration',
    icon: 'Droplets',
    color: '#0284c7', // Sky blue
    target: 8,
    unit: 'glasses',
    currentValue: 5,
    completed: false,
    minimumWin: {
      title: 'Quick 2 Glasses',
      description: 'Drink 2 full glasses of clean water immediately to hydrate vital organs.',
      value: 2,
      timeRequired: '1 min',
    },
    streak: 14,
    bestStreak: 21,
    frequency: 'daily',
    timeOfDay: 'Throughout Day',
    isPaused: false,
    history: {
      '2026-08-10': true,
      '2026-08-11': true,
      '2026-08-12': true,
      '2026-08-13': true,
      '2026-08-14': true,
      '2026-08-15': true,
      '2026-08-16': false,
    },
  },
  {
    id: 'habit-2',
    title: 'Daily Movement & Cardio',
    category: 'movement',
    icon: 'Flame',
    color: '#ea580c', // Orange
    target: 30,
    unit: 'minutes',
    currentValue: 0,
    completed: false,
    minimumWin: {
      title: '5-Minute Reset Stretch',
      description: 'Perform a gentle 5-minute dynamic spine & hip mobility flow.',
      value: 5,
      timeRequired: '5 min',
    },
    streak: 11,
    bestStreak: 18,
    frequency: 'daily',
    timeOfDay: 'Morning / Afternoon',
    isPaused: false,
    history: {
      '2026-08-10': true,
      '2026-08-11': true,
      '2026-08-12': true,
      '2026-08-13': false, // Triggered recovery win
      '2026-08-14': true,
      '2026-08-15': true,
      '2026-08-16': false,
    },
  },
  {
    id: 'habit-3',
    title: 'Restorative Sleep (7h 30m)',
    category: 'sleep',
    icon: 'Moon',
    color: '#6366f1', // Indigo
    target: 450, // 7.5 hours in minutes
    unit: 'minutes',
    currentValue: 440, // 7h 20m
    completed: true,
    minimumWin: {
      title: '15-Min Wind-down Meditation',
      description: 'Dim blue light and perform 4-7-8 deep diaphragmatic breathing.',
      value: 15,
      timeRequired: '15 min',
    },
    streak: 9,
    bestStreak: 15,
    frequency: 'daily',
    timeOfDay: 'Night',
    isPaused: false,
    history: {
      '2026-08-10': true,
      '2026-08-11': true,
      '2026-08-12': true,
      '2026-08-13': true,
      '2026-08-14': true,
      '2026-08-15': true,
      '2026-08-16': true,
    },
  },
  {
    id: 'habit-4',
    title: 'Mindful Breathwork',
    category: 'mindfulness',
    icon: 'HeartHandshake',
    color: '#0d9488', // Teal
    target: 10,
    unit: 'minutes',
    currentValue: 10,
    completed: true,
    minimumWin: {
      title: '2-Min Box Breathing',
      description: 'Inhale 4s, Hold 4s, Exhale 4s, Hold 4s to regulate autonomic nervous system.',
      value: 2,
      timeRequired: '2 min',
    },
    streak: 19,
    bestStreak: 25,
    frequency: 'daily',
    timeOfDay: 'Morning',
    isPaused: false,
    history: {
      '2026-08-10': true,
      '2026-08-11': true,
      '2026-08-12': true,
      '2026-08-13': true,
      '2026-08-14': true,
      '2026-08-15': true,
      '2026-08-16': true,
    },
  },
  {
    id: 'habit-5',
    title: 'Digital Sunset (No screens)',
    category: 'recovery',
    icon: 'SunDim',
    color: '#8b5cf6', // Purple/Violet
    target: 30,
    unit: 'minutes before bed',
    currentValue: 0,
    completed: false,
    minimumWin: {
      title: '5-Min Night Journaling',
      description: 'Write 3 highlights of your day and set tomorrow intention on paper.',
      value: 5,
      timeRequired: '5 min',
    },
    streak: 6,
    bestStreak: 12,
    frequency: 'daily',
    timeOfDay: 'Evening',
    isPaused: false,
    history: {
      '2026-08-10': true,
      '2026-08-11': true,
      '2026-08-12': true,
      '2026-08-13': false,
      '2026-08-14': true,
      '2026-08-15': true,
      '2026-08-16': false,
    },
  },
];

export const INITIAL_WEEK_STORY = [
  {
    date: '2026-08-10',
    dayShort: 'Mon',
    dayName: 'Monday',
    completionRate: 92,
    waterGlasses: 8,
    waterTarget: 8,
    sleepDuration: '7h 45m',
    sleepScore: 88,
    movementMinutes: 40,
    movementTarget: 30,
    mood: 'Energetic & Focused',
    moodScore: 9,
    highlights: 'Crushed morning cardio session and hit 8 glasses of hydration early.',
    habitsCompleted: 4,
    totalHabits: 5,
    recoveryUsed: false,
  },
  {
    date: '2026-08-11',
    dayShort: 'Tue',
    dayName: 'Tuesday',
    completionRate: 88,
    waterGlasses: 8,
    waterTarget: 8,
    sleepDuration: '7h 30m',
    sleepScore: 85,
    movementMinutes: 35,
    movementTarget: 30,
    mood: 'Calm & Consistent',
    moodScore: 8,
    highlights: 'Consistent adherence to medication and evening mindfulness.',
    habitsCompleted: 4,
    totalHabits: 5,
    recoveryUsed: false,
  },
  {
    date: '2026-08-12',
    dayShort: 'Wed',
    dayName: 'Wednesday (Best Day 🌟)',
    completionRate: 100,
    waterGlasses: 9,
    waterTarget: 8,
    sleepDuration: '8h 10m',
    sleepScore: 95,
    movementMinutes: 50,
    movementTarget: 30,
    mood: 'Peak Vitality & Flow',
    moodScore: 10,
    highlights: '100% Habit Completion! Personal best movement and sleep metrics recorded.',
    habitsCompleted: 5,
    totalHabits: 5,
    recoveryUsed: false,
  },
  {
    date: '2026-08-13',
    dayShort: 'Thu',
    dayName: 'Thursday',
    completionRate: 68,
    waterGlasses: 5,
    waterTarget: 8,
    sleepDuration: '6h 20m',
    sleepScore: 65,
    movementMinutes: 10,
    movementTarget: 30,
    mood: 'Slight Fatigue',
    moodScore: 6,
    highlights: 'Missed evening cardio due to late meetings, but claimed 5-min Minimum Win to keep momentum.',
    habitsCompleted: 3,
    totalHabits: 5,
    recoveryUsed: true,
  },
  {
    date: '2026-08-14',
    dayShort: 'Fri',
    dayName: 'Friday',
    completionRate: 86,
    waterGlasses: 8,
    waterTarget: 8,
    sleepDuration: '7h 35m',
    sleepScore: 84,
    movementMinutes: 35,
    movementTarget: 30,
    mood: 'Rebounded & Upbeat',
    moodScore: 8,
    highlights: 'Bounce-back day! Recovery protocol maintained streak successfully.',
    habitsCompleted: 4,
    totalHabits: 5,
    recoveryUsed: false,
  },
  {
    date: '2026-08-15',
    dayShort: 'Sat',
    dayName: 'Saturday',
    completionRate: 80,
    waterGlasses: 7,
    waterTarget: 8,
    sleepDuration: '8h 00m',
    sleepScore: 90,
    movementMinutes: 25,
    movementTarget: 30,
    mood: 'Relaxed & Restorative',
    moodScore: 8,
    highlights: 'Great weekend outdoor walk and deep sleep recharge.',
    habitsCompleted: 4,
    totalHabits: 5,
    recoveryUsed: false,
  },
  {
    date: '2026-08-16',
    dayShort: 'Sun',
    dayName: 'Sunday (Today)',
    completionRate: 82,
    waterGlasses: 5,
    waterTarget: 8,
    sleepDuration: '7h 20m',
    sleepScore: 82,
    movementMinutes: 0,
    movementTarget: 30,
    mood: 'Clear & Focused',
    moodScore: 8,
    highlights: 'Morning breathwork & sleep logged. Ready for afternoon movement minimum win.',
    habitsCompleted: 2,
    totalHabits: 5,
    recoveryUsed: false,
  },
];

export const INITIAL_MEDICATIONS = [
  {
    id: 'med-1',
    name: 'Vitamin D3 (Cholecalciferol)',
    dosage: '2,000 IU',
    form: 'Capsule',
    frequency: 'Daily with breakfast',
    scheduledTime: '08:00 AM',
    status: 'taken', // 'taken' | 'skipped' | 'pending'
    takenAt: '08:15 AM',
    prescribedFor: 'Bone density, mood support, immunity',
    remainingPills: 28,
    totalPills: 60,
    refillThreshold: 10,
    instructions: 'Take with healthy dietary fats for optimal absorption.',
  },
  {
    id: 'med-2',
    name: 'Omega-3 Super EPA / DHA',
    dosage: '1,200 mg',
    form: 'Softgel',
    frequency: 'Daily with lunch',
    scheduledTime: '01:00 PM',
    status: 'pending',
    takenAt: null,
    prescribedFor: 'Cardiovascular health & cognitive clarity',
    remainingPills: 45,
    totalPills: 90,
    refillThreshold: 15,
    instructions: 'Swallow with full glass of water after meal.',
  },
  {
    id: 'med-3',
    name: 'Magnesium Glycinate',
    dosage: '200 mg',
    form: 'Tablet',
    frequency: 'Daily before bed',
    scheduledTime: '09:30 PM',
    status: 'pending',
    takenAt: null,
    prescribedFor: 'Muscle relaxation & deep stage 3 sleep',
    remainingPills: 8, // Low stock -> trigger refill alert
    totalPills: 60,
    refillThreshold: 10,
    instructions: 'Take 45 minutes before sleep with chamomile tea or water.',
  },
  {
    id: 'med-4',
    name: 'Lisinopril (Preventive Cardio)',
    dosage: '5 mg',
    form: 'Tablet',
    frequency: 'Daily morning',
    scheduledTime: '08:00 AM',
    status: 'taken',
    takenAt: '08:12 AM',
    prescribedFor: 'Blood pressure optimization',
    remainingPills: 52,
    totalPills: 90,
    refillThreshold: 14,
    instructions: 'Maintain consistent daily timing.',
  },
];

export const INITIAL_CLINICS = [
  {
    id: 'clinic-1',
    name: 'City Central Medical Center & Emergency',
    category: 'hospital',
    type: 'Hospital & Level 1 Trauma Care',
    rating: 4.9,
    reviewsCount: 428,
    distanceMiles: 0.8,
    openStatus: 'Open 24/7',
    isOpen24Hours: true,
    emergencyCapable: true,
    address: '450 Sutter Health Way, Suite 100',
    phone: '+1 (555) 911-3000',
    lat: 37.7892,
    lng: -122.4089,
    image: IMAGES.clinics.cityCentral,
    specialties: ['Emergency Medicine', 'Cardiology', 'Trauma Care', 'Radiology', 'Neurology'],
    services: ['24/7 Emergency', 'Walk-in Care', 'CT/MRI Scans', 'ICU', 'Pharmacy'],
    waitTimeMinutes: 12,
  },
  {
    id: 'clinic-2',
    name: 'Bloom Wellness & Preventive Health Clinic',
    category: 'primary_care',
    type: 'Integrative Primary Care',
    rating: 4.95,
    reviewsCount: 312,
    distanceMiles: 1.2,
    openStatus: 'Open until 8:00 PM',
    isOpen24Hours: false,
    emergencyCapable: false,
    address: '820 Mission Boulevard, Fl 4',
    phone: '+1 (555) 782-4411',
    lat: 37.7833,
    lng: -122.4050,
    image: IMAGES.clinics.wellnessHub,
    specialties: ['Preventive Health', 'Family Medicine', 'Nutritional Care', 'Metabolic Health'],
    services: ['Routine Physicals', 'Biomarker Bloodwork', 'Longevity Assessment', 'Telehealth'],
    waitTimeMinutes: 5,
  },
  {
    id: 'clinic-3',
    name: 'Apex Rapid Urgent Care & Diagnostics',
    category: 'urgent_care',
    type: 'Walk-in Urgent Care & Lab',
    rating: 4.8,
    reviewsCount: 195,
    distanceMiles: 1.6,
    openStatus: 'Open 24/7',
    isOpen24Hours: true,
    emergencyCapable: true,
    address: '1240 Market Street, Suite B',
    phone: '+1 (555) 833-2900',
    lat: 37.7775,
    lng: -122.4167,
    image: IMAGES.clinics.urgentCare,
    specialties: ['Urgent Care', 'Rapid Testing', 'Minor Injury Repair', 'Infection Care'],
    services: ['Digital X-Ray', 'Rapid Lab Tests', 'IV Hydration', 'Stitch Care'],
    waitTimeMinutes: 8,
  },
  {
    id: 'clinic-4',
    name: 'St. Jude Heart & Vascular Specialty Clinic',
    category: 'specialist',
    type: 'Cardiovascular Institute',
    rating: 4.9,
    reviewsCount: 260,
    distanceMiles: 2.4,
    openStatus: 'Open until 6:00 PM',
    isOpen24Hours: false,
    emergencyCapable: false,
    address: '1500 California Street, Pavilion C',
    phone: '+1 (555) 602-9900',
    lat: 37.7915,
    lng: -122.4208,
    image: IMAGES.clinics.cardioSpecialty,
    specialties: ['Cardiology', 'Echocardiograms', 'Arrhythmia', 'Lipidology'],
    services: ['Stress Testing', 'Echo Scans', 'Heart Holter Monitors', 'Dietary Counseling'],
    waitTimeMinutes: 10,
  },
  {
    id: 'clinic-5',
    name: 'Pulse 24/7 Community Pharmacy & Clinic',
    category: 'pharmacy',
    type: '24/7 Pharmacy & Clinical Lab',
    rating: 4.75,
    reviewsCount: 154,
    distanceMiles: 0.5,
    openStatus: 'Open 24/7',
    isOpen24Hours: true,
    emergencyCapable: false,
    address: '600 Post Street',
    phone: '+1 (555) 441-2299',
    lat: 37.7878,
    lng: -122.4118,
    image: IMAGES.clinics.pharmacy24,
    specialties: ['Prescription Dispensing', 'Vaccinations', 'OTC Wellness', 'Health Consults'],
    services: ['Instant Med Delivery', 'Flu / Booster Shots', 'BP Check Machine', 'Med Review'],
    waitTimeMinutes: 2,
  },
];

export const INITIAL_APPOINTMENTS = [
  {
    id: 'apt-1',
    doctorName: 'Dr. Sarah Chen, MD, FACC',
    doctorAvatar: IMAGES.avatars.drChen,
    specialty: 'Cardiovascular Medicine & Longevity',
    clinicName: 'St. Jude Heart & Vascular Specialty Clinic',
    clinicAddress: '1500 California Street, Pavilion C',
    clinicId: 'clinic-4',
    date: '2026-08-17',
    time: '10:30 AM',
    type: 'In-Person', // 'In-Person' | 'Video Call'
    status: 'Upcoming', // 'Upcoming' | 'Completed' | 'Cancelled'
    purpose: 'Comprehensive Annual Cardio Screening & Lipid Panel',
    notes: 'Please arrive 10 minutes early. Fasting for 8 hours prior to blood draw is recommended.',
    phone: '+1 (555) 602-9900',
    directionsUrl: 'https://maps.google.com/?q=1500+California+Street+San+Francisco',
  },
  {
    id: 'apt-2',
    doctorName: 'Dr. Elena Rostova, MD',
    doctorAvatar: IMAGES.avatars.drElena,
    specialty: 'Integrative Medicine & Sleep Health',
    clinicName: 'Bloom Wellness & Preventive Health Clinic',
    clinicAddress: '820 Mission Boulevard, Fl 4',
    clinicId: 'clinic-2',
    date: '2026-08-24',
    time: '03:00 PM',
    type: 'Video Call',
    status: 'Upcoming',
    purpose: 'Biomarker Review & Habit Momentum Optimization',
    notes: 'Video link will be activated in app 15 minutes before the session.',
    phone: '+1 (555) 782-4411',
    videoLink: 'https://healthflow.app/telehealth/session-88912',
  },
  {
    id: 'apt-3',
    doctorName: 'Dr. Marcus Vance, DO',
    doctorAvatar: IMAGES.avatars.drMarcus,
    specialty: 'Primary Care & Sports Medicine',
    clinicName: 'City Central Medical Center',
    clinicAddress: '450 Sutter Health Way, Suite 100',
    clinicId: 'clinic-1',
    date: '2026-08-02',
    time: '09:00 AM',
    type: 'In-Person',
    status: 'Past',
    purpose: 'Routine Annual Physical & Vitals Check',
    notes: 'All vitals optimal. Resting BP 118/76 mmHg. Recommended keeping current hydration and Vitamin D supplementation.',
    phone: '+1 (555) 911-3000',
    doctorSummary: 'Patient in outstanding physical shape. Habit momentum score consistently above 80%.',
  },
];

export const INITIAL_AI_INSIGHTS = [
  {
    id: 'insight-1',
    category: 'hydration',
    title: 'Hydration Velocity Insight',
    description: 'You achieve 85% higher energy scores on days where you drink at least 4 glasses of water before 2:00 PM.',
    impact: '+18% Afternoon Focus',
    actionText: 'Drink Glass Now (+250ml)',
    actionType: 'add_water',
    time: '10:15 AM Today',
    isRead: false,
  },
  {
    id: 'insight-2',
    category: 'recovery',
    title: 'Minimum Win Multiplier',
    description: 'When you completed the 5-minute movement minimum win on Thursday, your habit streak was saved and momentum stayed at 82%.',
    impact: 'Protected 11-day streak',
    actionText: 'View Recovery Stats',
    actionType: 'view_recovery',
    time: 'Yesterday',
    isRead: true,
  },
  {
    id: 'insight-3',
    category: 'sleep',
    title: 'Deep Sleep & Evening Screen Correlation',
    description: 'Your stage 3 restorative sleep increased by 42 minutes on nights with digital sunset active before 10:30 PM.',
    impact: '+42 min Deep Sleep',
    actionText: 'Set Night Reminder',
    actionType: 'set_reminder',
    time: '2 days ago',
    isRead: true,
  },
];
